p.283 EditText에 String값을 저장하고 다시 불러오기
onPaused가 호출되면 Error 발생
* E/AndroidRuntime: FATAL EXCEPTION: main
      Process: com.example.samplelifecycle, PID: 12474
      java.lang.RuntimeException: Unable to pause activity {com.example.samplelifecycle/com.example.samplelifecycle.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference
          at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4503)
          at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4454)
          at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4406)
          at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
          at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
          at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
          at android.os.Handler.dispatchMessage(Handler.java:107)
          at android.os.Looper.loop(Looper.java:214)
          at android.app.ActivityThread.main(ActivityThread.java:7356)
          at java.lang.reflect.Method.invoke(Native Method)
          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference
          at com.example.samplelifecycle.MainActivity.saveState(MainActivity.java:76)
          at com.example.samplelifecycle.MainActivity.onPause(MainActivity.java:57)
          at android.app.Activity.performPause(Activity.java:7978)
          at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1500)
          at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4493)
          at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4454) 
          at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4406) 
          at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46) 
          at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
          at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
          at android.os.Handler.dispatchMessage(Handler.java:107) 
          at android.os.Looper.loop(Looper.java:214) 
          at android.app.ActivityThread.main(ActivityThread.java:7356) 
          at java.lang.reflect.Method.invoke(Native Method) 
          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 